#$ -cwd
#$ -q Annotation-3
#$ -pe mpich 40
#$ -S /bin/bash

module load Bowtie2/v2.3.3.1
module load samtools/v1.9
module load bcftools/v1.9
module load snpEff/v.4.3t

for DIR in `find ./* -maxdepth 0 -type d`; do
	if [ -f ${DIR}/pipeline.done ]; then
		continue
	else

	DIR=${DIR#./}

	MATE1=${DIR}/*R1*.fastq.gz
	MATE2=${DIR}/*R2*.fastq.gz

	# Bowtie2 mapping
	mkdir ${DIR}/Bowtie2


	bowtie2-build --threads $NSLOTS Skeletonema_marinoi_Ref_v1.1.1.fst ${DIR}/Bowtie2/${DIR}.contigs
	

	bowtie2 -p $NSLOTS --no-unal --very-sensitive -x ${DIR}/Bowtie2/${DIR}.contigs -1 $MATE1 -2 $MATE2 -S ${DIR}/Bowtie2/${DIR}.sam
		

	samtools view -Sb ${DIR}/Bowtie2/${DIR}.sam > ${DIR}/Bowtie2/${DIR}.bam
		rm ${DIR}/Bowtie2/${DIR}.sam

	samtools sort ${DIR}/Bowtie2/${DIR}.bam -o ${DIR}/Bowtie2/${DIR}_sorted.bam
		rm ${DIR}/Bowtie2/${DIR}.bam

	samtools index ${DIR}/Bowtie2/${DIR}_sorted.bam ${DIR}/Bowtie2/${DIR}_sorted.bai
		
	# Variant calling
        mkdir ${DIR}/Vcalling

        samtools mpileup -u -g -f Skeletonema_marinoi_Ref_v1.1.1.fst ${DIR}/Bowtie2/${DIR}_sorted.bam | bcftools call -v -m -O z -o ${DIR}/Vcalling/outputvcffile.mpileup.vcf.gz

	# Variant annotation and effect prediction

	snpEff -no-downstream -no-upstream -no-intron -no-intergenic -classic Skeletonema_marinoi_v1.1.1.1 -stats ${DIR}/Vcalling/snpEff_summary.html ${DIR}/Vcalling/outputvcffile.mpileup.vcf.gz > ${DIR}/Vcalling/snpeff_annotated.vcf

	# Filter and manipulation annotated files

	cat ${DIR}/Vcalling/snpeff_annotated.vcf | java -jar /usr/local/packages/snpEff/SnpSift.jar filter "(QUAL>=10)&(DP>=10)" > ${DIR}/Vcalling/snpeff_annotated_filtered.vcf

	# Mark the sample as finished
	touch ${DIR}/pipeline.done
	fi 

done
